# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: talKKonnect test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Set up Go
      uses: actions/checkout@v4
      
    - name: Build
      run: cd /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect & go build -x -o /home/talkkonnect/bin/talkkonnect cmd/talkkonnect/main.go
